name: git-release
on:
  push:
    branches:
      - release/*

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_changelog: ${{ steps.git-cliff.outputs.content }}
      release_version: ${{ steps.git-cliff.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version
        id: release-version
        run: |
          echo "version=$( echo '${{ github.ref_name }}' | sed 's|release/||' )" >> $GITHUB_OUTPUT

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --unreleased --tag ${{ steps.release-version.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md

  release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ needs.changelog.outputs.release_version }}
          body: ${{ needs.changelog.outputs.release_changelog }}
